"""call transcription and topic classification

Revision ID: 006d139a8ae5
Revises: 3f4e77c2e742
Create Date: 2026-10-02 11:14:35.864697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006d139a8ae5'
down_revision: Union[str, None] = '3f4e77c2e742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telephony_calls', sa.Column('transcript_status', sa.String(length=20), nullable=True))
    op.add_column('telephony_calls', sa.Column('transcript_text', sa.Text(), nullable=True))
    op.add_column('telephony_calls', sa.Column('topic_tag', sa.String(length=20), nullable=True))
    op.add_column('telephony_calls', sa.Column('transcript_error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_telephony_calls_transcript_status'), 'telephony_calls', ['transcript_status'], unique=False)
    op.add_column('telephony_settings', sa.Column('classify_calls_enabled', sa.Boolean(), server_default='false', nullable=False))
    # server_default so the existing singleton telephony_settings row (see
    # services/telephony_settings_service.py) doesn't violate NOT NULL.
    op.add_column(
        'telephony_settings',
        sa.Column(
            'yandexgpt_model', sa.String(length=50), server_default='yandexgpt-lite/latest', nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telephony_settings', 'yandexgpt_model')
    op.drop_column('telephony_settings', 'classify_calls_enabled')
    op.drop_index(op.f('ix_telephony_calls_transcript_status'), table_name='telephony_calls')
    op.drop_column('telephony_calls', 'transcript_error')
    op.drop_column('telephony_calls', 'topic_tag')
    op.drop_column('telephony_calls', 'transcript_text')
    op.drop_column('telephony_calls', 'transcript_status')
    # ### end Alembic commands ###
