"""workshop phone mapping and call workshop columns

Revision ID: 088dd8ec7b7e
Revises: 1fc55af48b7b
Create Date: 2026-10-04 12:08:09.213876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '088dd8ec7b7e'
down_revision: Union[str, None] = '1fc55af48b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_phone_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workshop_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('phone IS NOT NULL OR extension IS NOT NULL', name=op.f('ck_workshop_phone_mappings_phone_or_extension')),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], name=op.f('fk_workshop_phone_mappings_workshop_id_workshops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_phone_mappings'))
    )
    op.create_index(op.f('ix_workshop_phone_mappings_extension'), 'workshop_phone_mappings', ['extension'], unique=False)
    op.create_index(op.f('ix_workshop_phone_mappings_phone'), 'workshop_phone_mappings', ['phone'], unique=False)
    op.create_index(op.f('ix_workshop_phone_mappings_workshop_id'), 'workshop_phone_mappings', ['workshop_id'], unique=False)
    op.add_column('telephony_calls', sa.Column('dst', sa.String(length=100), nullable=True))
    op.add_column('telephony_calls', sa.Column('exten', sa.String(length=20), nullable=True))
    op.add_column('telephony_calls', sa.Column('rang_extensions', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('telephony_calls', sa.Column('workshop_id', sa.UUID(), nullable=True))
    op.add_column('telephony_calls', sa.Column('workshop_source', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_telephony_calls_workshop_id'), 'telephony_calls', ['workshop_id'], unique=False)
    op.create_foreign_key(op.f('fk_telephony_calls_workshop_id_workshops'), 'telephony_calls', 'workshops', ['workshop_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_telephony_calls_workshop_id_workshops'), 'telephony_calls', type_='foreignkey')
    op.drop_index(op.f('ix_telephony_calls_workshop_id'), table_name='telephony_calls')
    op.drop_column('telephony_calls', 'workshop_source')
    op.drop_column('telephony_calls', 'workshop_id')
    op.drop_column('telephony_calls', 'rang_extensions')
    op.drop_column('telephony_calls', 'exten')
    op.drop_column('telephony_calls', 'dst')
    op.drop_index(op.f('ix_workshop_phone_mappings_workshop_id'), table_name='workshop_phone_mappings')
    op.drop_index(op.f('ix_workshop_phone_mappings_phone'), table_name='workshop_phone_mappings')
    op.drop_index(op.f('ix_workshop_phone_mappings_extension'), table_name='workshop_phone_mappings')
    op.drop_table('workshop_phone_mappings')
    # ### end Alembic commands ###
