"""add planner workshop_jobs, body_cars, body_car_stages

Revision ID: 1e1aba094f72
Revises: 4130c1773083
Create Date: 2026-09-21 08:15:34.317758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1aba094f72'
down_revision: Union[str, None] = '4130c1773083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_cars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workshop_id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('car_description', sa.String(length=500), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('plate', sa.String(length=20), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_body_cars_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_body_cars_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_body_cars_work_order_id_work_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], name=op.f('fk_body_cars_workshop_id_workshops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_cars'))
    )
    op.create_index(op.f('ix_body_cars_work_order_id'), 'body_cars', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_body_cars_workshop_id'), 'body_cars', ['workshop_id'], unique=False)
    op.create_table('workshop_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workshop_id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('car_description', sa.String(length=500), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('plate', sa.String(length=20), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('job_date', sa.Date(), nullable=False),
    sa.Column('post_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('norm_hours', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_workshop_jobs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['slesarka_statuses.id'], name=op.f('fk_workshop_jobs_status_id_slesarka_statuses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_workshop_jobs_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_workshop_jobs_work_order_id_work_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], name=op.f('fk_workshop_jobs_workshop_id_workshops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_jobs'))
    )
    op.create_index(op.f('ix_workshop_jobs_job_date'), 'workshop_jobs', ['job_date'], unique=False)
    op.create_index(op.f('ix_workshop_jobs_work_order_id'), 'workshop_jobs', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_workshop_jobs_workshop_id'), 'workshop_jobs', ['workshop_id'], unique=False)
    op.create_table('body_car_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('body_car_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['body_car_id'], ['body_cars.id'], name=op.f('fk_body_car_stages_body_car_id_body_cars'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_car_stages'))
    )
    op.create_index(op.f('ix_body_car_stages_body_car_id'), 'body_car_stages', ['body_car_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_body_car_stages_body_car_id'), table_name='body_car_stages')
    op.drop_table('body_car_stages')
    op.drop_index(op.f('ix_workshop_jobs_workshop_id'), table_name='workshop_jobs')
    op.drop_index(op.f('ix_workshop_jobs_work_order_id'), table_name='workshop_jobs')
    op.drop_index(op.f('ix_workshop_jobs_job_date'), table_name='workshop_jobs')
    op.drop_table('workshop_jobs')
    op.drop_index(op.f('ix_body_cars_workshop_id'), table_name='body_cars')
    op.drop_index(op.f('ix_body_cars_work_order_id'), table_name='body_cars')
    op.drop_table('body_cars')
    # ### end Alembic commands ###
