"""add work order payment fields and history

Revision ID: 3a785672624b
Revises: d37d82b77fe2
Create Date: 2026-09-16 12:24:57.937268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a785672624b'
down_revision: Union[str, None] = 'd37d82b77fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_payment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deal_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('debt_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_payment_history_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_payment_history'))
    )
    op.create_index(op.f('ix_work_order_payment_history_observed_at'), 'work_order_payment_history', ['observed_at'], unique=False)
    op.create_index(op.f('ix_work_order_payment_history_work_order_id'), 'work_order_payment_history', ['work_order_id'], unique=False)
    op.add_column('work_orders', sa.Column('deal_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('work_orders', sa.Column('debt_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('work_orders', sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('work_orders', sa.Column('payment_percent', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'payment_percent')
    op.drop_column('work_orders', 'paid_amount')
    op.drop_column('work_orders', 'debt_amount')
    op.drop_column('work_orders', 'deal_amount')
    op.drop_index(op.f('ix_work_order_payment_history_work_order_id'), table_name='work_order_payment_history')
    op.drop_index(op.f('ix_work_order_payment_history_observed_at'), table_name='work_order_payment_history')
    op.drop_table('work_order_payment_history')
    # ### end Alembic commands ###
