"""employee phone and birth_date, drop phone_exclusions

Revision ID: 3f4e77c2e742
Revises: 6a0b37df2a43
Create Date: 2026-09-30 13:38:40.563598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f4e77c2e742'
down_revision: Union[str, None] = '6a0b37df2a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phone_exclusions_phone', table_name='phone_exclusions')
    op.drop_table('phone_exclusions')
    op.add_column('employees', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('employees', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'birth_date')
    op.drop_column('employees', 'phone')
    op.create_table('phone_exclusions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_phone_exclusions')
    )
    op.create_index('ix_phone_exclusions_phone', 'phone_exclusions', ['phone'], unique=True)
    # ### end Alembic commands ###
