"""add users, departments, workshops, slesarka_statuses, schedule_audit_log

Revision ID: 4130c1773083
Revises: 546506a82d27
Create Date: 2026-09-21 07:22:00.897382

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4130c1773083'
down_revision: Union[str, None] = '546506a82d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Seed data required by the product brief - not derived from app code (a
# migration must keep working exactly as written even if
# app/services/auth_service.py's hashing later changes), so the PBKDF2
# hash below is a literal, computed once with today's algorithm
# (hashlib.pbkdf2_hmac("sha256", ..., 260_000 iterations), see
# auth_service.hash_password) for the seeded admin password "2305".
_PAN_ADMIN_PASSWORD_HASH = (
    "02307e6a661cc4e0aa6b1942a1262e30$"
    "999da50e9b55fc6edc28cdf7157d7e2848acea1a9fb74427e281a0aa25c81b1c"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('slesarka_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slesarka_statuses')),
    sa.UniqueConstraint('name', name=op.f('uq_slesarka_statuses_name'))
    )
    op.create_table('workshops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('workshop_type', sa.String(length=20), nullable=False),
    sa.Column('area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('working_days', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_workshops_department_id_departments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshops'))
    )
    op.create_index(op.f('ix_workshops_department_id'), 'workshops', ['department_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('workshop_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], name=op.f('fk_users_workshop_id_workshops'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('schedule_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_schedule_audit_log_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_audit_log'))
    )
    op.create_index(op.f('ix_schedule_audit_log_created_at'), 'schedule_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_schedule_audit_log_entity_id'), 'schedule_audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_schedule_audit_log_entity_type'), 'schedule_audit_log', ['entity_type'], unique=False)
    # ### end Alembic commands ###

    # ---- seed data required by the product brief ----
    departments_table = sa.table('departments', sa.column('id', sa.UUID()), sa.column('name', sa.String()))
    kakhovka_id = uuid.uuid4()
    solntsevo_id = uuid.uuid4()
    op.bulk_insert(departments_table, [
        {'id': kakhovka_id, 'name': 'Каховка'},
        {'id': solntsevo_id, 'name': 'Солнцево'},
    ])

    users_table = sa.table(
        'users',
        sa.column('id', sa.UUID()),
        sa.column('full_name', sa.String()),
        sa.column('login', sa.String()),
        sa.column('password_hash', sa.String()),
        sa.column('role', sa.String()),
    )
    op.bulk_insert(users_table, [{
        'id': uuid.uuid4(),
        'full_name': 'Пан Оксана Игоревна',
        'login': 'PanAdmin',
        'password_hash': _PAN_ADMIN_PASSWORD_HASH,
        'role': 'Админ',
    }])

    statuses_table = sa.table(
        'slesarka_statuses', sa.column('id', sa.UUID()), sa.column('name', sa.String()), sa.column('color', sa.String())
    )
    op.bulk_insert(statuses_table, [
        {'id': uuid.uuid4(), 'name': 'Запись', 'color': '#5b6b82'},
        {'id': uuid.uuid4(), 'name': 'В работе', 'color': '#e59a0c'},
        {'id': uuid.uuid4(), 'name': 'Готова', 'color': '#17924a'},
        {'id': uuid.uuid4(), 'name': 'Отмена', 'color': '#d83232'},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_audit_log_entity_type'), table_name='schedule_audit_log')
    op.drop_index(op.f('ix_schedule_audit_log_entity_id'), table_name='schedule_audit_log')
    op.drop_index(op.f('ix_schedule_audit_log_created_at'), table_name='schedule_audit_log')
    op.drop_table('schedule_audit_log')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_workshops_department_id'), table_name='workshops')
    op.drop_table('workshops')
    op.drop_table('slesarka_statuses')
    op.drop_table('departments')
    # ### end Alembic commands ###
