"""call quality assessment

Revision ID: 6a9dbc9750fa
Revises: 088dd8ec7b7e
Create Date: 2026-10-04 13:44:30.123296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9dbc9750fa'
down_revision: Union[str, None] = '088dd8ec7b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telephony_calls', sa.Column('quality_score', sa.Integer(), nullable=True))
    op.add_column('telephony_calls', sa.Column('quality_review', sa.Text(), nullable=True))
    op.add_column('telephony_settings', sa.Column('assess_quality_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telephony_settings', 'assess_quality_enabled')
    op.drop_column('telephony_calls', 'quality_review')
    op.drop_column('telephony_calls', 'quality_score')
    # ### end Alembic commands ###
