"""add payer_name to work_orders

Revision ID: 6b3aed739c53
Revises: c44e2b7acfd1
Create Date: 2026-09-13 11:52:38.413483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3aed739c53'
down_revision: Union[str, None] = 'c44e2b7acfd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('payer_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'payer_name')
    # ### end Alembic commands ###
