"""add phone exclusions

Revision ID: 87c9177524f9
Revises: e6419db77276
Create Date: 2026-09-30 10:17:33.992854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c9177524f9'
down_revision: Union[str, None] = 'e6419db77276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_exclusions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_exclusions'))
    )
    op.create_index(op.f('ix_phone_exclusions_phone'), 'phone_exclusions', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_exclusions_phone'), table_name='phone_exclusions')
    op.drop_table('phone_exclusions')
    # ### end Alembic commands ###
