"""initial schema: work_orders and import_batches

Revision ID: c44e2b7acfd1
Revises: 
Create Date: 2026-09-13 07:11:32.030719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c44e2b7acfd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_index(op.f('ix_import_batches_batch_id'), 'import_batches', ['batch_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_number', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=50), server_default='alpha-auto', nullable=False),
    sa.Column('source_key', sa.String(length=200), nullable=True),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('vehicle_description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders')),
    sa.UniqueConstraint('source_system', 'external_number', name='uq_work_orders_source_system_external_number')
    )
    op.create_index(op.f('ix_work_orders_external_number'), 'work_orders', ['external_number'], unique=False)
    op.create_index(op.f('ix_work_orders_source_key'), 'work_orders', ['source_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_source_key'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_external_number'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_import_batches_batch_id'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
