"""add work order status history

Revision ID: d071c553e42f
Revises: dbdd275599e8
Create Date: 2026-09-15 15:12:42.219554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd071c553e42f'
down_revision: Union[str, None] = 'dbdd275599e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_status_history_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_status_history'))
    )
    op.create_index(op.f('ix_work_order_status_history_last_seen_at'), 'work_order_status_history', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_work_order_status_history_work_order_id'), 'work_order_status_history', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_status_history_work_order_id'), table_name='work_order_status_history')
    op.drop_index(op.f('ix_work_order_status_history_last_seen_at'), table_name='work_order_status_history')
    op.drop_table('work_order_status_history')
    # ### end Alembic commands ###
