"""add created_date, start_date, end_date, closed_date to work orders

Revision ID: dbdd275599e8
Revises: e2923330d3a6
Create Date: 2026-09-13 15:33:54.388102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdd275599e8'
down_revision: Union[str, None] = 'e2923330d3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('work_orders', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('work_orders', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('work_orders', sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_work_orders_closed_date'), 'work_orders', ['closed_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_closed_date'), table_name='work_orders')
    op.drop_column('work_orders', 'closed_date')
    op.drop_column('work_orders', 'end_date')
    op.drop_column('work_orders', 'start_date')
    op.drop_column('work_orders', 'created_date')
    # ### end Alembic commands ###
