"""add status, department, labor and parts lines to work orders

Revision ID: e2923330d3a6
Revises: 6b3aed739c53
Create Date: 2026-09-13 13:43:44.315969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2923330d3a6'
down_revision: Union[str, None] = '6b3aed739c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_labor_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('operation_name', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_labor_lines_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_labor_lines'))
    )
    op.create_index(op.f('ix_work_order_labor_lines_work_order_id'), 'work_order_labor_lines', ['work_order_id'], unique=False)
    op.create_table('work_order_part_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_part_lines_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_part_lines'))
    )
    op.create_index(op.f('ix_work_order_part_lines_work_order_id'), 'work_order_part_lines', ['work_order_id'], unique=False)
    op.add_column('work_orders', sa.Column('status', sa.String(length=100), nullable=True))
    op.add_column('work_orders', sa.Column('department', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_work_orders_department'), 'work_orders', ['department'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_department'), table_name='work_orders')
    op.drop_column('work_orders', 'department')
    op.drop_column('work_orders', 'status')
    op.drop_index(op.f('ix_work_order_part_lines_work_order_id'), table_name='work_order_part_lines')
    op.drop_table('work_order_part_lines')
    op.drop_index(op.f('ix_work_order_labor_lines_work_order_id'), table_name='work_order_labor_lines')
    op.drop_table('work_order_labor_lines')
    # ### end Alembic commands ###
