"""add website leads and leads settings

Revision ID: e6419db77276
Revises: b77e8b85ed0a
Create Date: 2026-09-29 08:16:28.581746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6419db77276'
down_revision: Union[str, None] = 'b77e8b85ed0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('intake_token', sa.String(length=100), nullable=True),
    sa.Column('stale_after_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads_settings'))
    )
    op.create_table('website_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('photos', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_leads'))
    )
    op.create_index(op.f('ix_website_leads_created_at'), 'website_leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_website_leads_phone'), 'website_leads', ['phone'], unique=False)
    op.create_index(op.f('ix_website_leads_source'), 'website_leads', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_leads_source'), table_name='website_leads')
    op.drop_index(op.f('ix_website_leads_phone'), table_name='website_leads')
    op.drop_index(op.f('ix_website_leads_created_at'), table_name='website_leads')
    op.drop_table('website_leads')
    op.drop_table('leads_settings')
    # ### end Alembic commands ###
